# Generated by Django 3.2.5 on 2021-08-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210809_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrowers',
        ),
    ]
